# Generated by Django 2.0.3 on 2018-04-14 19:23

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('geoposts', '0002_experiment_results_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_result', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='experiment',
            name='results_json',
            field=jsonfield.fields.JSONField(blank=True),
        ),
        migrations.AddField(
            model_name='instructorresult',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoposts.Experiment'),
        ),
    ]
