# Generated by Django 2.0.2 on 2018-03-06 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoposts', '0002_auto_20180305_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoposts',
            name='geoproject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoposts.Geoproject'),
        ),
    ]
