# Generated by Django 2.0.3 on 2018-04-01 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoposts', '0003_auto_20180401_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='geopoststudent',
            name='grade',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='geopost',
            name='geoproject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoposts.Geoproject'),
        ),
    ]
