# Generated by Django 2.0.3 on 2018-04-14 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoposts', '0003_auto_20180414_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorresult',
            name='experiment',
        ),
        migrations.DeleteModel(
            name='InstructorResult',
        ),
    ]
