# Generated by Django 2.0.2 on 2018-03-18 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoposts', '0006_auto_20180317_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='geopost',
        ),
        migrations.AddField(
            model_name='geoposts',
            name='experiment',
            field=models.ManyToManyField(to='geoposts.Experiment'),
        ),
        migrations.AlterField(
            model_name='geoposts',
            name='geoproject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoposts.Geoproject'),
        ),
    ]
