# Generated by Django 2.0.3 on 2018-03-22 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoposts', '0007_auto_20180317_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geoposts',
            old_name='image',
            new_name='image_instructor',
        ),
        migrations.AddField(
            model_name='geoposts',
            name='image_student',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='geoposts',
            name='geoproject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoposts.Geoproject'),
        ),
    ]
