# Generated by Django 2.0.3 on 2018-03-22 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoposts', '0008_auto_20180321_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geoposts',
            old_name='image_instructor',
            new_name='image_instructor_five_instructor',
        ),
        migrations.AddField(
            model_name='geoposts',
            name='image_instructor_four_instructor',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geoposts',
            name='image_instructor_one_instructor',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geoposts',
            name='image_instructor_three_instructor',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geoposts',
            name='image_instructor_two_instructor',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='geoposts',
            name='geoproject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoposts.Geoproject'),
        ),
    ]
