# Generated by Django 2.0.3 on 2018-04-16 01:36

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('geoposts', '0008_instructor_results_my_specimen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='result',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='results_json',
        ),
        migrations.AddField(
            model_name='instructor_results',
            name='result',
            field=jsonfield.fields.JSONField(default=1),
            preserve_default=False,
        ),
    ]
