# Generated by Django 2.0.3 on 2018-04-16 01:43

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('geoposts', '0009_auto_20180416_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor_results',
            name='result',
        ),
        migrations.AddField(
            model_name='instructor_results',
            name='result_json',
            field=jsonfield.fields.JSONField(blank=True),
        ),
    ]
