# Generated by Django 2.0.3 on 2018-03-22 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoposts', '0009_auto_20180321_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='geoposts',
            name='image_instructor_five_instructor',
        ),
        migrations.RemoveField(
            model_name='geoposts',
            name='image_instructor_four_instructor',
        ),
        migrations.RemoveField(
            model_name='geoposts',
            name='image_instructor_one_instructor',
        ),
        migrations.RemoveField(
            model_name='geoposts',
            name='image_instructor_three_instructor',
        ),
        migrations.RemoveField(
            model_name='geoposts',
            name='image_instructor_two_instructor',
        ),
        migrations.RemoveField(
            model_name='geoposts',
            name='image_student',
        ),
        migrations.AlterField(
            model_name='geoposts',
            name='geoproject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoposts.Geoproject'),
        ),
        migrations.AddField(
            model_name='geoposts',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geoposts.Images'),
            preserve_default=False,
        ),
    ]
