# Generated by Django 2.0.3 on 2018-03-22 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoposts', '0010_auto_20180321_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoposts',
            name='geoproject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoposts.Geoproject'),
        ),
        migrations.RemoveField(
            model_name='geoposts',
            name='image',
        ),
        migrations.AddField(
            model_name='geoposts',
            name='image',
            field=models.ManyToManyField(to='geoposts.Images'),
        ),
    ]
