# Generated by Django 2.0.3 on 2018-04-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoposts', '0011_instructor_results_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='option_five',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='experiment',
            name='option_four',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='experiment',
            name='option_one',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='experiment',
            name='option_seven',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='experiment',
            name='option_six',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='experiment',
            name='option_three',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='experiment',
            name='option_two',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
