# Generated by Django 2.0.3 on 2018-03-26 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoposts', '0017_auto_20180323_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='geopoststudent',
            name='geo_post_id',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='geopost',
            name='geoproject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoposts.Geoproject'),
        ),
    ]
