# Generated by Django 2.0.3 on 2018-03-26 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoposts', '0018_auto_20180325_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geopost',
            name='geoproject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoposts.Geoproject'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='geocaching_images'),
        ),
    ]
