# Generated by Django 2.0.3 on 2018-03-26 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoposts', '0020_auto_20180326_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geopost',
            name='geoproject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoposts.Geoproject'),
        ),
    ]
